"""
Example script to cluster the embeddings generated by deberta_embeddings.py

This script shows how to:
1. Load embeddings
2. Apply clustering (KMeans)
3. Save cluster labels back to CSV
"""

import torch
import pandas as pd
import os
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from tqdm import tqdm

AUDIO_ROOT = "./data"
EMBEDDING_FILE = "_embeddings.pt"
FILTERED_CSV = "_transcribed_filtered.csv"

def cluster_embeddings(embeddings, n_clusters=5, apply_pca=True, n_components=50):
    """
    Cluster embeddings using KMeans.
    
    Args:
        embeddings: PyTorch tensor of shape (n_samples, embedding_dim)
        n_clusters: Number of clusters to create
        apply_pca: Whether to apply PCA before clustering
        n_components: Number of PCA components if applying PCA
        
    Returns:
        labels: Cluster labels for each sample
    """
    # Convert to numpy
    emb_np = embeddings.numpy()
    
    # Optional: Standardize (z-score normalization)
    print("  Standardizing embeddings...")
    scaler = StandardScaler()
    emb_scaled = scaler.fit_transform(emb_np)
    
    # Optional: Reduce dimensionality with PCA
    if apply_pca:
        print(f"  Applying PCA with {n_components} components...")
        pca = PCA(n_components=n_components)
        emb_reduced = pca.fit_transform(emb_scaled)
        print(f"  Explained variance: {pca.explained_variance_ratio_.sum():.2%}")
    else:
        emb_reduced = emb_scaled
    
    # Run KMeans clustering
    print(f"  Clustering into {n_clusters} groups...")
    kmeans = KMeans(n_clusters=n_clusters, random_state=0, n_init=10)
    labels = kmeans.fit_predict(emb_reduced)
    
    return labels

def cluster_all_subfolders(n_clusters=5):
    """Cluster embeddings for all subfolders"""
    
    subfolders = sorted(os.listdir(AUDIO_ROOT))
    print(f"Found {len(subfolders)} subfolders\n")
    
    for subfolder in tqdm(subfolders, desc="Processing folders", unit="folder"):
        subfolder_path = os.path.join(AUDIO_ROOT, subfolder)
        
        # Check if both embedding file and CSV exist
        embedding_path = os.path.join(subfolder_path, f"{subfolder}{EMBEDDING_FILE}")
        csv_path = os.path.join(subfolder_path, f"{subfolder}{FILTERED_CSV}")
        output_csv = os.path.join(subfolder_path, f"{subfolder}_with_clusters.csv")
        
        if not os.path.isfile(embedding_path) or not os.path.isfile(csv_path):
            tqdm.write(f"⚠️  Skipping {subfolder}: missing files")
            continue
        
        if os.path.isfile(output_csv):
            tqdm.write(f"⏭️  Skipping {subfolder}: already clustered")
            continue
        
        try:
            # Load embeddings
            tqdm.write(f"\n📁 Processing: {subfolder}")
            embeddings = torch.load(embedding_path)
            
            # Load CSV data
            df = pd.read_csv(csv_path)
            
            if len(embeddings) != len(df):
                tqdm.write(f"⚠️  Mismatch: {len(embeddings)} embeddings vs {len(df)} rows")
                continue
            
            # Cluster embeddings
            labels = cluster_embeddings(embeddings, n_clusters=n_clusters)
            
            # Add cluster labels to dataframe
            df['cluster'] = labels
            
            # Show cluster distribution
            cluster_counts = pd.Series(labels).value_counts().sort_index()
            tqdm.write(f"  Cluster sizes: {dict(cluster_counts)}")
            
            # Show sample from each cluster
            print("\nSample transcriptions from each cluster:")
            for cluster_id in range(n_clusters):
                cluster_texts = df[df['cluster'] == cluster_id]['transcription'].head(2)
                print(f"\n  Cluster {cluster_id} ({len(df[df['cluster'] == cluster_id])} items):")
                for idx, text in enumerate(cluster_texts):
                    print(f"    [{idx+1}] {text[:80]}...")
            
            # Save results
            df.to_csv(output_csv, index=False)
            tqdm.write(f"✅ Saved clustered data to {output_csv}")
            
        except Exception as e:
            tqdm.write(f"❌ Failed to process {subfolder}: {str(e)}")
    
    print(f"\n{'='*50}")
    print("✨ Clustering complete!")
    print(f"{'='*50}")

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description='Cluster embeddings')
    parser.add_argument('--n_clusters', type=int, default=5, help='Number of clusters')
    parser.add_argument('--no_pca', action='store_true', help='Skip PCA dimension reduction')
    
    args = parser.parse_args()
    
    cluster_all_subfolders(
        n_clusters=args.n_clusters,
        apply_pca=not args.no_pca
    )

