"""
Example script to read and use the embeddings generated by deberta_embeddings.py

Each embedding file contains a PyTorch tensor where:
- Shape: (num_transcriptions, embedding_dimension)
- embedding_dimension = 768 for DeBERTa-v3-base
"""

import torch
import pandas as pd
import os

AUDIO_ROOT = "./data"
EMBEDDING_FILE = "_embeddings.pt"
FILTERED_CSV = "_transcribed_filtered.csv"

def load_embeddings_and_data(subfolder_name):
    """
    Load embeddings and corresponding CSV data for a subfolder.
    
    Returns:
        embeddings: PyTorch tensor of shape (n_samples, 768)
        df: DataFrame with transcription data
    """
    subfolder_path = os.path.join(AUDIO_ROOT, subfolder_name)
    
    # Load embeddings
    embedding_path = os.path.join(subfolder_path, f"{subfolder_name}{EMBEDDING_FILE}")
    embeddings = torch.load(embedding_path)
    
    # Load corresponding CSV
    csv_path = os.path.join(subfolder_path, f"{subfolder_name}{FILTERED_CSV}")
    df = pd.read_csv(csv_path)
    
    print(f"Loaded {len(embeddings)} embeddings from {subfolder_name}")
    print(f"Embedding shape: {embeddings.shape}")
    print(f"Number of transcriptions in CSV: {len(df)}")
    
    return embeddings, df

def example_usage():
    """Example of how to use the embeddings"""
    
    # Get list of all subfolders with embeddings
    subfolders = sorted(os.listdir(AUDIO_ROOT))
    
    for subfolder in subfolders:
        embedding_path = os.path.join(AUDIO_ROOT, subfolder, f"{subfolder}{EMBEDDING_FILE}")
        
        if os.path.isfile(embedding_path):
            print(f"\n{'='*60}")
            print(f"Processing: {subfolder}")
            print(f"{'='*60}")
            
            # Load embeddings and data
            embeddings, df = load_embeddings_and_data(subfolder)
            
            # Example 1: Get statistics
            print(f"\nEmbedding statistics:")
            print(f"  Mean: {embeddings.mean().item():.4f}")
            print(f"  Std:  {embeddings.std().item():.4f}")
            print(f"  Min:  {embeddings.min().item():.4f}")
            print(f"  Max:  {embeddings.max().item():.4f}")
            
            # Example 2: Show first few transcriptions and their embeddings
            print(f"\nFirst 3 transcriptions:")
            for i in range(min(3, len(df))):
                print(f"  [{i}] {df.iloc[i]['transcription'][:80]}...")
                print(f"       Embedding shape: {embeddings[i].shape}")
                print(f"       First 5 values: {embeddings[i][:5]}")
            
            # Example 3: Compute similarity between first two transcriptions
            if len(embeddings) >= 2:
                import torch.nn.functional as F
                # Normalize for cosine similarity
                emb_norm = F.normalize(embeddings[:2], p=2, dim=1)
                similarity = torch.mm(emb_norm, emb_norm.t())[0, 1]
                print(f"\nCosine similarity between first two transcriptions: {similarity:.4f}")
            
            # Example 4: Compare transcriptions
            print(f"\nComparisons:")
            trans1 = df.iloc[0]['transcription'][:60]
            trans2 = df.iloc[1]['transcription'][:60] if len(df) > 1 else "N/A"
            print(f"  Trans1: {trans1}...")
            print(f"  Trans2: {trans2}...")
            
            break  # Just show the first subfolder as an example

if __name__ == "__main__":
    example_usage()

